import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Akira = localFont({
  src: [
    {
      path: "../public/fonts/Akira/Akira Expanded Demo.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-Akira",
});

const NeueMontreal = localFont({
  src: [
    {
      path: "../public/fonts/NeueMontreal/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-NeueMontreal",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${Akira.variable} ${NeueMontreal.variable}`}
    >
      <body className="min-h-full flex flex-col bg-sky-100">
       
        {children}
       <Footer/>
        </body>
    </html>
  );
}
